export const sourceProfiles = {
    greenhouse: {
        type: "greenhouse",
        label: "Greenhouse",
        extractionMode: "api",
        supportLevel: "supported",
        canRun: true,
        summary: "Structured board API adapter.",
    },
    lever: {
        type: "lever",
        label: "Lever",
        extractionMode: "api",
        supportLevel: "supported",
        canRun: true,
        summary: "Structured posting API adapter.",
    },
    workday: {
        type: "workday",
        label: "Workday",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected Workday portal using generic extraction with browser fallback.",
    },
    icims: {
        type: "icims",
        label: "iCIMS",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected iCIMS portal using generic extraction with browser fallback.",
    },
    smartrecruiters: {
        type: "smartrecruiters",
        label: "SmartRecruiters",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected SmartRecruiters portal using generic extraction with browser fallback.",
    },
    ashby: {
        type: "ashby",
        label: "Ashby",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected Ashby board using generic extraction with browser fallback.",
    },
    bamboohr: {
        type: "bamboohr",
        label: "BambooHR",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected BambooHR board using generic extraction with browser fallback.",
    },
    taleo: {
        type: "taleo",
        label: "Taleo",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected Taleo or Oracle Recruiting page using generic extraction with browser fallback.",
    },
    oracle: {
        type: "oracle",
        label: "Oracle Careers",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected Oracle careers page using generic extraction with browser fallback.",
    },
    microsoft: {
        type: "microsoft",
        label: "Microsoft Careers",
        extractionMode: "browser",
        supportLevel: "browser-required",
        canRun: true,
        summary: "Detected Microsoft Careers using browser-backed extraction.",
    },
    "generic-html": {
        type: "generic-html",
        label: "Generic careers page",
        extractionMode: "html",
        supportLevel: "detected",
        canRun: true,
        summary: "Detected a likely careers page using generic extraction with browser fallback.",
    },
    "browser-required": {
        type: "browser-required",
        label: "Browser-backed portal",
        extractionMode: "browser",
        supportLevel: "browser-required",
        canRun: true,
        summary: "Detected a portal that runs through the hidden browser extractor.",
    },
    unsupported: {
        type: "unsupported",
        label: "Unknown source",
        extractionMode: "unknown",
        supportLevel: "manual-review",
        canRun: false,
        summary: "No reliable extraction path has been detected yet.",
    },
};
export function getSourceProfile(type) {
    return sourceProfiles[type] ?? sourceProfiles.unsupported;
}
export function canRunSourceType(type) {
    return getSourceProfile(type).canRun;
}
